import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path_ from 'node:path';
import { analyzeCorrection, Candle, classifyCorrectionDepth, computeCorrectionMaturity, CorrectionCandidate } from '../server/corrections.js';
import { CorrectionLifecycleStore } from '../server/correctionLifecycle.js';
import { CorrectionValidationStore } from '../server/correctionValidations.js';

// Correction maturity (age + retracement depth) is informational only. These
// tests pin the anchor rules and prove nothing else in the scanner moved.

// ── deterministic fixtures ──────────────────────────────────────────────────
// Existing-suite style waves (same as scripts/test_corrections.ts).
function wave(count: number, start: number, slope: number, amplitude = 2, period = 12): Candle[] {
  return Array.from({ length: count }, (_, index) => {
    const close = start + slope * index + Math.sin(index * Math.PI * 2 / period) * amplitude;
    const open = close - slope * .2;
    return { t: new Date(Date.UTC(2025, 0, 1, index)).toISOString(), o: open, h: Math.max(open, close) + .35, l: Math.min(open, close) - .35, c: close, v: 100 };
  });
}
function fixture(dailySlope: number, h4Slope: number, h1Slope: number) {
  const daily = wave(240, 100, dailySlope, 2.5);
  const current = daily.at(-1)!.c;
  const h4 = wave(160, current - h4Slope * 159, h4Slope, 1.3);
  const h1 = wave(120, current - h1Slope * 119, h1Slope, .65);
  const m30 = wave(100, current + 2, h1Slope, .4);
  return { daily, h4, h1, m30, livePrice: h1.at(-1)!.c };
}
// Piecewise-linear 1H path through exact pivot nodes; doji candles (o=h=l=c)
// so every swing extreme is exactly the node price.
function path(nodes: Array<[number, number]>): Candle[] {
  const out: Candle[] = [];
  for (let n = 0; n < nodes.length - 1; n++) {
    const [i0, p0] = nodes[n]; const [i1, p1] = nodes[n + 1];
    for (let i = i0; i < i1; i++) {
      const price = i === i0 ? p0 : p0 + (p1 - p0) * (i - i0) / (i1 - i0);
      out.push({ t: new Date(Date.UTC(2025, 5, 1, i)).toISOString(), o: price, h: price, l: price, c: price, v: 100 });
    }
  }
  const [last, lastPrice] = nodes.at(-1)!;
  out.push({ t: new Date(Date.UTC(2025, 5, 1, last)).toISOString(), o: lastPrice, h: lastPrice, l: lastPrice, c: lastPrice, v: 100 });
  return out;
}
const mirror = (candles: Candle[], axis: number): Candle[] => candles.map(c => ({ ...c, o: axis - c.o, h: axis - c.l, l: axis - c.h, c: axis - c.c }));
// Surfaced-candidate fixtures: Daily thesis from fixture(); 1H path with a
// complete bullish leg (turn low b-6 after an earlier higher low) up to the
// b+4 peak, then a confirmed counter-structure (lower low + lower high).
function structuredBullish() {
  const base = fixture(.08, .025, -.035);
  const b = Math.round(base.daily.at(-1)!.c);
  const h1 = path([[0, b - 3], [8, b - 4.5], [16, b - 3.5], [26, b - 6], [38, b - 2], [48, b - 5], [62, b + 4], [74, b - 6.5], [84, b - 1], [94, b - 3]]);
  return { ...base, h1, livePrice: h1.at(-1)!.c, b };
}
function structuredBearish() {
  const base = fixture(-.08, -.025, .035);
  const b = Math.round(base.daily.at(-1)!.c);
  const h1 = mirror(path([[0, b - 3], [8, b - 4.5], [16, b - 3.5], [26, b - 6], [38, b - 2], [48, b - 5], [62, b + 4], [74, b - 6.5], [84, b - 1], [94, b - 3]]), 2 * b);
  return { ...base, h1, livePrice: h1.at(-1)!.c, b };
}
const SNAPSHOT_CASES = (): Record<string, [string, any]> => ({
  bull: ['EUR_USD', fixture(.08, .025, -.035)],
  bear: ['GBP_USD', fixture(-.08, -.025, .035)],
  aligned: ['USD_JPY', fixture(.08, .025, .035)],
  ranging: ['EUR_GBP', fixture(0, 0, -.02)],
  structuredBullish: ['EUR_USD', structuredBullish()],
  structuredBearish: ['GBP_USD', structuredBearish()],
});
const stripVolatile = (result: any) => {
  if (!result.candidate) return result;
  const { scannedAt, maturity, ...rest } = result.candidate;
  return { candidate: rest };
};

// What the base commit 4dfa502 returned for SNAPSHOT_CASES (scannedAt and
// the new maturity field removed). Generated by running 4dfa502's
// analyzeCorrection on these exact builders.
const BASE_4DFA502 = {
 "bull": {
  "candidate": {
   "pair": "EUR_USD",
   "thesisDirection": "LONG",
   "correctionDirection": "SHORT",
   "stage": "CORRECTION_IN_PROGRESS",
   "price": 117.54499999999999,
   "dailyStructure": "LONG",
   "h4Structure": "LONG",
   "h1Leg": "SHORT",
   "thesisBasis": [
    "Daily bullish swing structure",
    "Daily close remains inside 115.13400 invalidation",
    "Price supports 200 SMA context"
   ],
   "location": {
    "atLocation": false,
    "approaching": false,
    "labels": [
     "4H demand away"
    ],
    "primaryLabel": "4H demand away",
    "zone": {
     "type": "DEMAND",
     "timeframe": "H4",
     "low": 116.06500000000001,
     "high": 116.42,
     "formedAt": "2025-01-07T09:00:00.000Z",
     "ageCandles": 6,
     "freshness": "TESTED_ONCE",
     "touches": 1,
     "state": "AWAY",
     "distance": 1.1249999999999858,
     "distanceAtr": 1.59,
     "distancePips": 11250,
     "distancePercent": 0.957
    },
    "nearestLevel": 116.06500000000001,
    "distanceAtr": 2.092084006462017
   },
   "confirmation30m": {
    "shiftDetected": false,
    "retestSeen": false
   },
   "invalidation": {
    "timeframe": "D",
    "level": 115.134,
    "rule": "Thesis dies only if a completed Daily structural candle closes below this level."
   },
   "correctionQuality": {
    "cleanCounterLeg": true,
    "legAtr": 1.6,
    "bars": 24,
    "extended": false
   },
   "priority": 75,
   "priorityReasons": [
    "Clear Daily swing thesis",
    "Price agrees with Daily 200 SMA context",
    "4H thesis remains aligned",
    "Clean 1H counter-leg"
   ],
   "exposure": [
    "EUR",
    "USD"
   ]
  }
 },
 "bear": {
  "candidate": {
   "pair": "GBP_USD",
   "thesisDirection": "SHORT",
   "correctionDirection": "LONG",
   "stage": "CORRECTION_IN_PROGRESS",
   "price": 79.30499999999998,
   "dailyStructure": "SHORT",
   "h4Structure": "SHORT",
   "h1Leg": "LONG",
   "thesisBasis": [
    "Daily bearish swing structure",
    "Daily close remains inside 84.38600 invalidation",
    "Price supports 200 SMA context"
   ],
   "location": {
    "atLocation": false,
    "approaching": false,
    "labels": [
     "4H supply away"
    ],
    "primaryLabel": "4H supply away",
    "zone": {
     "type": "SUPPLY",
     "timeframe": "H4",
     "low": 81.22999999999998,
     "high": 81.58499999999997,
     "formedAt": "2025-01-07T03:00:00.000Z",
     "ageCandles": 12,
     "freshness": "TESTED_TWICE",
     "touches": 2,
     "state": "AWAY",
     "distance": 1.9249999999999972,
     "distanceAtr": 2.72,
     "distancePips": 19250,
     "distancePercent": 2.427
    },
    "nearestLevel": 81.58499999999997,
    "distanceAtr": 3.2229402261712545
   },
   "confirmation30m": {
    "shiftDetected": false,
    "retestSeen": false
   },
   "invalidation": {
    "timeframe": "D",
    "level": 84.386,
    "rule": "Thesis dies only if a completed Daily structural candle closes above this level."
   },
   "correctionQuality": {
    "cleanCounterLeg": true,
    "legAtr": 0.68,
    "bars": 24,
    "extended": false
   },
   "priority": 75,
   "priorityReasons": [
    "Clear Daily swing thesis",
    "Price agrees with Daily 200 SMA context",
    "4H thesis remains aligned",
    "Clean 1H counter-leg"
   ],
   "exposure": [
    "GBP",
    "USD"
   ]
  }
 },
 "aligned": {
  "other": {
   "pair": "USD_JPY",
   "state": "ALIGNED_TREND",
   "reason": "The active 1H leg is not moving against the Daily thesis."
  }
 },
 "ranging": {
  "other": {
   "pair": "EUR_GBP",
   "state": "NO_CLEAR_THESIS",
   "reason": "Daily swing structure is mixed or ranging."
  }
 },
 "structuredBullish": {
  "candidate": {
   "pair": "EUR_USD",
   "thesisDirection": "LONG",
   "correctionDirection": "SHORT",
   "stage": "AT_LOCATION",
   "price": 115,
   "dailyStructure": "LONG",
   "h4Structure": "LONG",
   "h1Leg": "SHORT",
   "thesisBasis": [
    "Daily bullish swing structure",
    "Daily close remains inside 115.13400 invalidation",
    "Price supports 200 SMA context"
   ],
   "location": {
    "atLocation": true,
    "approaching": false,
    "labels": [
     "4H demand zone",
     "HTF support/resistance",
     "HTF discount"
    ],
    "primaryLabel": "4H demand zone",
    "zone": {
     "type": "DEMAND",
     "timeframe": "H4",
     "low": 114.86500000000001,
     "high": 115.22,
     "formedAt": "2025-01-05T09:00:00.000Z",
     "ageCandles": 54,
     "freshness": "TESTED_TWICE",
     "touches": 2,
     "state": "IN_ZONE",
     "distance": 0,
     "distanceAtr": 0,
     "distancePips": 0,
     "distancePercent": 0
    },
    "nearestLevel": 114.86500000000001,
    "distanceAtr": 0.44999999999996937
   },
   "confirmation30m": {
    "shiftDetected": false,
    "retestSeen": false
   },
   "invalidation": {
    "timeframe": "D",
    "level": 115.134,
    "rule": "Thesis dies only if a completed Daily structural candle closes below this level."
   },
   "correctionQuality": {
    "cleanCounterLeg": false,
    "legAtr": 2.92,
    "bars": 24,
    "extended": true
   },
   "priority": 55,
   "priorityReasons": [
    "Clear Daily swing thesis",
    "Price agrees with Daily 200 SMA context",
    "4H thesis remains aligned",
    "At 4H demand zone",
    "Correction is near invalidation or already extended"
   ],
   "exposure": [
    "EUR",
    "USD"
   ]
  }
 },
 "structuredBearish": {
  "candidate": {
   "pair": "GBP_USD",
   "thesisDirection": "SHORT",
   "correctionDirection": "LONG",
   "stage": "AT_LOCATION",
   "price": 83,
   "dailyStructure": "SHORT",
   "h4Structure": "SHORT",
   "h1Leg": "LONG",
   "thesisBasis": [
    "Daily bearish swing structure",
    "Daily close remains inside 84.38600 invalidation",
    "Price supports 200 SMA context"
   ],
   "location": {
    "atLocation": true,
    "approaching": false,
    "labels": [
     "4H supply zone",
     "HTF support/resistance"
    ],
    "primaryLabel": "4H supply zone",
    "zone": {
     "type": "SUPPLY",
     "timeframe": "H4",
     "low": 82.72999999999998,
     "high": 83.08499999999997,
     "formedAt": "2025-01-04T15:00:00.000Z",
     "ageCandles": 72,
     "freshness": "TESTED_TWICE",
     "touches": 2,
     "state": "IN_ZONE",
     "distance": 0,
     "distanceAtr": 0,
     "distancePips": 0,
     "distancePercent": 0
    },
    "nearestLevel": 83.08499999999997,
    "distanceAtr": 0.28333333333321753
   },
   "confirmation30m": {
    "shiftDetected": false,
    "retestSeen": false
   },
   "invalidation": {
    "timeframe": "D",
    "level": 84.386,
    "rule": "Thesis dies only if a completed Daily structural candle closes above this level."
   },
   "correctionQuality": {
    "cleanCounterLeg": false,
    "legAtr": 2.92,
    "bars": 24,
    "extended": false
   },
   "priority": 80,
   "priorityReasons": [
    "Clear Daily swing thesis",
    "Price agrees with Daily 200 SMA context",
    "4H thesis remains aligned",
    "At 4H supply zone"
   ],
   "exposure": [
    "GBP",
    "USD"
   ]
  }
 }
};

// Unit path (USD_JPY, pip 0.01). Swing lows 98 @8, 95 @26 (turn), 100 @46;
// swing highs 103 @16, 105 @36, 120 @61. Bullish impulse 95 -> 120 (25),
// correction starts at the 120 pivot (bar 61 = correction bar 0) and runs to
// `end` at bar 71 (correction bar 10).
const unitPath = (end: number, ...tail: Array<[number, number]>) =>
  path([[0, 104], [8, 98], [16, 103], [26, 95], [36, 105], [46, 100], [61, 120], [71, end], ...tail]);

// 1. bullish Daily thesis + bearish 1H correction
{
  const candles = unitPath(110);
  const m = computeCorrectionMaturity('USD_JPY', candles, 'LONG');
  assert.equal(m.correctionStartTime, candles[61].t);
  assert.equal(m.correctionStartPrice, 120);
  assert.equal(m.correctionEndPrice, 110);
  assert.equal(m.correctionDistancePrice, 10);
  assert.equal(m.correctionDistancePips, 1000);
  assert.equal(m.correctionDistancePercent, 8.333);
  assert.equal(m.priorImpulseStartTime, candles[26].t, 'impulse starts at the turn low, not the last higher low');
  assert.equal(m.priorImpulseEndTime, candles[61].t);
  assert.equal(m.priorImpulseStartPrice, 95);
  assert.equal(m.priorImpulseEndPrice, 120);
  assert.equal(m.priorImpulseDistance, 25);
  assert.equal(m.retracementPercent, 40);
}

// 2. bearish Daily thesis + bullish 1H correction (mirror image)
{
  const m = computeCorrectionMaturity('USD_JPY', mirror(unitPath(110), 200), 'SHORT');
  assert.equal(m.correctionStartPrice, 80);
  assert.equal(m.correctionEndPrice, 90);
  assert.equal(m.priorImpulseStartPrice, 105);
  assert.equal(m.priorImpulseEndPrice, 80);
  assert.equal(m.retracementPercent, 40);
  assert.equal(m.correctionDepth, 'DEVELOPING');
}

// 3 / 4 / 5. depth labels (descriptive thresholds 33 / 66)
assert.equal(computeCorrectionMaturity('USD_JPY', unitPath(115), 'LONG').correctionDepth, 'SHALLOW');    // 20%
assert.equal(computeCorrectionMaturity('USD_JPY', unitPath(110), 'LONG').correctionDepth, 'DEVELOPING'); // 40%
assert.equal(computeCorrectionMaturity('USD_JPY', unitPath(100), 'LONG').correctionDepth, 'DEEP');       // 80%
assert.deepEqual([32.99, 33, 65.99, 66, 150].map(classifyCorrectionDepth), ['SHALLOW', 'DEVELOPING', 'DEVELOPING', 'DEEP', 'DEEP']);
assert.equal(classifyCorrectionDepth(null), null);
assert.equal(classifyCorrectionDepth(Number.NaN), null);

// 6. exactly 50% => crossedEquilibrium true (49.6% => false)
{
  const exact = computeCorrectionMaturity('USD_JPY', unitPath(107.5), 'LONG');
  assert.equal(exact.retracementPercent, 50);
  assert.equal(exact.crossedEquilibrium, true);
  const below = computeCorrectionMaturity('USD_JPY', unitPath(107.6), 'LONG');
  assert.equal(below.retracementPercent, 49.6);
  assert.equal(below.crossedEquilibrium, false);
}

// 7 / 8. age counts completed 1H bars after the start pivot; the pivot is bar 0
{
  const candles = unitPath(110);
  const m = computeCorrectionMaturity('USD_JPY', candles, 'LONG');
  assert.equal(m.correctionStartTime, candles[61].t, 'start pivot candle is bar 0');
  assert.equal(m.correctionAgeBars, 10, 'bars 62..71 are correction bars 1..10');
  assert.equal(computeCorrectionMaturity('USD_JPY', unitPath(110, [72, 109]), 'LONG').correctionAgeBars, 11);
}

// 9. a forming (complete === false) 1H candle changes neither age nor anchors
{
  const candles = unitPath(110);
  const forming = { ...candles.at(-1)!, t: new Date(Date.UTC(2025, 5, 1, 72)).toISOString(), o: 110, h: 110, l: 96, c: 96, complete: false } as Candle;
  assert.deepEqual(computeCorrectionMaturity('USD_JPY', [...candles, forming], 'LONG'), computeCorrectionMaturity('USD_JPY', candles, 'LONG'));
  // and live price never enters the maturity calculation
  const f = structuredBullish();
  const a = analyzeCorrection({ pair: 'EUR_USD', ...f }).candidate!;
  const b = analyzeCorrection({ pair: 'EUR_USD', ...f, livePrice: f.livePrice + 3 }).candidate!;
  assert.deepEqual(a.maturity, b.maturity);
}

// 10. missing anchors => null fields, safely (never fabricated)
{
  const allNull = (m: object) => Object.values(m).every(value => value === null);
  assert.ok(allNull(computeCorrectionMaturity('EUR_USD', fixture(.08, .025, -.035).h1, 'LONG')), 'unbroken trend: start not identifiable in history');
  assert.ok(allNull(computeCorrectionMaturity('EUR_USD', unitPath(110).slice(0, 5), 'LONG')), 'too few candles');
  assert.ok(allNull(computeCorrectionMaturity('EUR_USD', [], 'LONG')), 'no candles');
  assert.ok(allNull(computeCorrectionMaturity('USD_JPY', unitPath(115, [68, 121], [69, 119]), 'LONG')), 'start pivot exceeded by a later completed candle');
  // start found, but the impulse's higher-low sequence runs back to the start of history:
  // age/distance kept, impulse + retracement null.
  const noTurn = computeCorrectionMaturity('USD_JPY', path([[0, 101], [10, 103], [20, 99], [30, 105], [40, 100], [55, 120], [65, 110]]), 'LONG');
  assert.equal(noTurn.correctionAgeBars, 10);
  assert.equal(noTurn.correctionStartPrice, 120);
  assert.equal(noTurn.priorImpulseStartPrice, null);
  assert.equal(noTurn.retracementPercent, null);
  assert.equal(noTurn.correctionDepth, null);
  assert.equal(noTurn.crossedEquilibrium, null);
}

// 11. a correction stays surfaced when maturity is unavailable
{
  const result = analyzeCorrection({ pair: 'EUR_USD', ...fixture(.08, .025, -.035) });
  assert.ok(result.candidate, 'still a candidate');
  assert.equal(result.candidate!.maturity?.retracementPercent, null);
  assert.equal(result.candidate!.maturity?.correctionDepth, null);
}

// Surfaced candidates carry maturity from their completed 1H leg
{
  const bull = analyzeCorrection({ pair: 'EUR_USD', ...structuredBullish() }).candidate!;
  assert.equal(bull.thesisDirection, 'LONG');
  assert.equal(bull.correctionDirection, 'SHORT');
  assert.equal(bull.maturity?.correctionAgeBars, 32);
  assert.equal(bull.maturity?.retracementPercent, 105);
  assert.equal(bull.maturity?.correctionDepth, 'DEEP');
  assert.equal(bull.maturity?.crossedEquilibrium, true);
  const bear = analyzeCorrection({ pair: 'GBP_USD', ...structuredBearish() }).candidate!;
  assert.equal(bear.thesisDirection, 'SHORT');
  assert.equal(bear.correctionDirection, 'LONG');
  assert.equal(bear.maturity?.retracementPercent, 105);
}

// 12 / 13. qualification, stage, location/HTF zones, priority: identical to 4dfa502
for (const [name, [pair, f]] of Object.entries(SNAPSHOT_CASES())) {
  assert.deepEqual(JSON.parse(JSON.stringify(stripVolatile(analyzeCorrection({ pair, ...f })))), (BASE_4DFA502 as any)[name], `${name} unchanged vs 4dfa502`);
}

// 14 / 15. lifecycle stages and validation linkage are unchanged by maturity
{
  const dir = await fs.mkdtemp(path_.join(os.tmpdir(), 'maturity-'));
  const f = structuredBullish();
  const candidate = analyzeCorrection({ pair: 'EUR_USD', ...f }).candidate!;
  const withoutMaturity = (c: CorrectionCandidate) => { const copy = structuredClone(c); delete copy.maturity; return copy; };
  const market = new Map([['EUR_USD', { daily: f.daily, h1: f.h1, m30: f.m30, m5: f.m30 }]]);
  const now = '2026-10-01T12:00:00.000Z';
  const runOnce = async (tag: string, c: CorrectionCandidate) => {
    const lifecycle = new CorrectionLifecycleStore(path_.join(dir, `life-${tag}.json`));
    const validations = new CorrectionValidationStore(path_.join(dir, `val-${tag}.json`));
    const reconciled = await lifecycle.reconcile([c], market, new Set(), now);
    await validations.create({ pair: c.pair, correctionEpisodeId: c.episodeId, scanTimestamp: now, dailyThesis: c.thesisDirection,
      h4Context: String(c.h4Structure), h1CorrectionLeg: c.correctionDirection, h1CorrectionStage: c.stage, locationContext: c.location.primaryLabel });
    const synced = await validations.syncLifecycle([c]);
    return { stage: c.stage, lifecycle: reconciled, validations: synced.map(({ createdAt, updatedAt, ...rest }) => rest) };
  };
  const a = await runOnce('with', structuredClone(candidate));
  const b = await runOnce('without', withoutMaturity(candidate));
  assert.deepEqual(a, b, 'lifecycle + validation linkage identical with or without maturity');
  await fs.rm(dir, { recursive: true, force: true });
}

console.log('Correction maturity tests passed: bullish/bearish anchors, shallow/developing/deep, 50% equilibrium, completed-bar age, pivot bar 0, forming candle ignored, null-safe, still surfaced, qualification/zones unchanged vs 4dfa502, lifecycle + validation unchanged.');
